# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "soundbox-sp"
client_id = "2e7c0654220bac9751fa220320174800"
application_url = "https://expansys-conversations-drag-computers.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,read_orders,write_price_rules,read_price_rules,read_discounts,write_discounts"

[auth]
redirect_urls = [
  "https://expansys-conversations-drag-computers.trycloudflare.com/auth/callback",
  "https://expansys-conversations-drag-computers.trycloudflare.com/auth/shopify/callback",
  "https://expansys-conversations-drag-computers.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "soundboxdev.myshopify.com"
