# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "quelldesign subscription"
client_id = "d59381d0a3f4f9a250fca30d6d0d5775"
application_url = "https://quelldesign-subscription.hieunguyen.dev"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,read_orders,write_price_rules,read_price_rules,read_discounts,write_discounts"

[auth]
redirect_urls = [
  "https://quelldesign-subscription.hieunguyen.dev/auth/callback",
  "https://quelldesign-subscription.hieunguyen.dev/auth/shopify/callback",
  "https://quelldesign-subscription.hieunguyen.dev/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "soundboxdev.myshopify.com"
