# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "plugin-sbs-subscription"
client_id = "630f22c9d054058af83186aac630ad6b"
application_url = "https://jump-oops-planes-airfare.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,read_orders,write_price_rules,read_price_rules,read_discounts,write_discounts"

[auth]
redirect_urls = [
  "https://jump-oops-planes-airfare.trycloudflare.com/auth/callback",
  "https://jump-oops-planes-airfare.trycloudflare.com/auth/shopify/callback",
  "https://jump-oops-planes-airfare.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "soundboxdev.myshopify.com"
