# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "plugin-subscription"
client_id = "a1b2fc5f328819ca821266a6622ee9f5"
application_url = "https://lender-secondary-voters-mariah.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,read_orders,read_files,write_files"

[auth]
redirect_urls = [
  "https://lender-secondary-voters-mariah.trycloudflare.com/auth/callback",
  "https://lender-secondary-voters-mariah.trycloudflare.com/auth/shopify/callback",
  "https://lender-secondary-voters-mariah.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "soundboxdev.myshopify.com"
